import { ProjectWork, CapabilityItem } from "./types";

export const STUDIO_INFO = {
  availability: "AVAILABLE FOR 2035",
  email: "info@mysite.com",
  phone: "123-456-7890",
  address: "500 Terry Francine St. San Francisco, CA 94158",
};

export const PROJECTS_DATA: ProjectWork[] = [
  {
    id: "blue-shift",
    title: "The Blue Shift",
    subtitle: "Magazine Design & Merchandise",
    category: "Magazine Design & Merchandise",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=1000",
    year: "2035",
    client: "Blue Shift Publications",
    description: "Experimental typography and bound editorial publication focusing on optical grid systems and physical merchandise alignment.",
    tags: ["Editorial", "Print", "Typography", "Merchandise"],
    aspectRatio: "square",
    featured: true,
  },
  {
    id: "oryx-coffee",
    title: "Oryx Coffee Lab Cans",
    subtitle: "Beverage Packaging & Brand System",
    category: "Packaging & Spatial",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=1000",
    year: "2034",
    client: "Oryx Coffee Roasters",
    description: "Hand-drawn daisy iconography paired with tactile aluminum craft cans for cold brew coffee extractions.",
    tags: ["Packaging", "Can Design", "Iconography"],
    aspectRatio: "portrait",
    featured: true,
  },
  {
    id: "jazz-brunch",
    title: "Weekend Jazz Brunch",
    subtitle: "Poster & Event Visual Language",
    category: "Brand Identity",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=1000",
    year: "2035",
    client: "Le Petit Bistro",
    description: "Minimalist poster design featuring high-contrast macro photography of buttered artisan toast with custom serif headings.",
    tags: ["Poster Design", "Art Direction", "Event"],
    aspectRatio: "square",
    featured: true,
  },
  {
    id: "coffee-pouch",
    title: "Artisan Coffee Beans",
    subtitle: "Sustainable Packaging & Label System",
    category: "Packaging & Spatial",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&q=80&w=1000",
    year: "2034",
    client: "Single Origin Co.",
    description: "Translucent biodegradable pouches adorned with fluorescent neon tracking stickers and batch origin codes.",
    tags: ["Packaging", "Sustainability", "Typography"],
    aspectRatio: "portrait",
    featured: true,
  },
  {
    id: "the-remade",
    title: "The Remade Magazine",
    subtitle: "Urban Waste Into Long-Life Objects",
    category: "Editorial Systems",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=1000",
    year: "2035",
    client: "The Remade Studio",
    description: "Bilingual editorial spread highlighting circular economy furniture designs and industrial re-use manifestos.",
    tags: ["Editorial", "Magazine Spread", "Industrial Design"],
    aspectRatio: "landscape",
    featured: true,
  },
  {
    id: "berlin-poster",
    title: "Exhibition 22.01-26.02.2035",
    subtitle: "Street Posters & Wayfinding",
    category: "Digital Visual Language",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=1000",
    year: "2035",
    client: "Berlin Neue Galerie",
    description: "Experimental photography combined with vibrant orange structural bounding boxes and high-contrast date typography.",
    tags: ["Poster", "Street Art", "Photography"],
    aspectRatio: "portrait",
    featured: true,
  },
  {
    id: "toulouse",
    title: "Toulouse Bar & Bistro",
    subtitle: "Digital Menu & Identity System",
    category: "Digital Visual Language",
    image: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&q=80&w=1000",
    year: "2034",
    client: "Toulouse Dining Group",
    description: "Rich burgundy tablet display experience juxtaposed against warm leather interior tones.",
    tags: ["Digital Menu", "Restaurant Identity", "UX/UI"],
    aspectRatio: "landscape",
    featured: true,
  },
];

export const CAPABILITIES_DATA: CapabilityItem[] = [
  {
    id: "brand-identity",
    title: "Brand Strategy & Visual Systems",
    description: "We define core visual logic, typographic hierarchies, and brand guidelines that adapt seamlessly across print and digital media.",
    services: ["Identity Design", "Brand Guidelines", "Design Systems", "Tone of Voice"],
    featuredProject: "Weekend Jazz Brunch",
  },
  {
    id: "editorial-merchandise",
    title: "Magazine Design & Merchandise",
    description: "Art direction for print, editorial layouts, custom physical goods, and apparel that bridge publication and product design.",
    services: ["Publication Layout", "Merchandise Design", "Book Design", "Print Management"],
    featuredProject: "The Blue Shift",
  },
  {
    id: "packaging-spatial",
    title: "Packaging & Environmental Graphics",
    description: "Tactile material selection, structural package design, and spatial wayfinding systems engineered for physical impact.",
    services: ["Structural Packaging", "Label Systems", "Exhibition Graphics", "Material Sourcing"],
    featuredProject: "Oryx Coffee Lab Cans",
  },
  {
    id: "digital-visual",
    title: "Digital Visual Languages & Interfaces",
    description: "Translating complex digital architectures into effortless, high-contrast user experiences built for modern displays.",
    services: ["UX/UI Design", "Interactive Art Direction", "Digital Menus", "Motion Design"],
    featuredProject: "Toulouse Bar & Bistro",
  },
];

export const STUDIO_PROFILE = {
  heading: "Design is an act of translation. It is about turning complex business logic into intuitive visual languages. No fluff, just impact.",
  manifesto: "Founded in San Francisco, GLYPH & chroma operates at the intersection of rigorous typography, editorial structure, and tactile physical production. We partner with visionaries, institutions, and progressive brands to create enduring aesthetic systems.",
  stats: [
    { label: "Founded", value: "2024" },
    { label: "Projects Completed", value: "140+" },
    { label: "Design Awards", value: "18" },
    { label: "Global Clients", value: "24 Countries" },
  ],
  servicesSummary: "This is the space to introduce your Services section. Briefly describe the types of services you offer and highlight any special benefits or features.",
};
